/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * TPS.AI API
 * API para apoio à Terapia Ocupacional — processamento e integração sensorial
 * OpenAPI spec version: 0.0.1
 */
import { customFetch } from "../../fetch";
export type GetMe200 = {
  id: string;
  name: string;
  email: string;
  /** @nullable */
  image: string | null;
};

export type GetMe401 = {
  error: string;
  code: string;
};

export type GetMe500 = {
  error: string;
  code: string;
};

export type ListPatientsParams = {
  activeOnly?: ListPatientsActiveOnly;
};

export type ListPatientsActiveOnly =
  (typeof ListPatientsActiveOnly)[keyof typeof ListPatientsActiveOnly];

export const ListPatientsActiveOnly = {
  true: "true",
  false: "false",
} as const;

export type ListPatients200PatientsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ListPatients200 = {
  patients: ListPatients200PatientsItem[];
};

export type ListPatients401 = {
  error: string;
  code: string;
};

export type ListPatients500 = {
  error: string;
  code: string;
};

export type CreatePatientBody = {
  /** @minLength 1 */
  name: string;
  /** @nullable */
  notes?: string | null;
};

export type CreatePatient201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type CreatePatient401 = {
  error: string;
  code: string;
};

export type CreatePatient500 = {
  error: string;
  code: string;
};

export type GetPatient200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type GetPatient401 = {
  error: string;
  code: string;
};

export type GetPatient404 = {
  error: string;
  code: string;
};

export type GetPatient500 = {
  error: string;
  code: string;
};

export type UpdatePatientBody = {
  /** @minLength 1 */
  name?: string;
  /** @nullable */
  notes?: string | null;
  isActive?: boolean;
};

export type UpdatePatient200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  notes: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type UpdatePatient401 = {
  error: string;
  code: string;
};

export type UpdatePatient404 = {
  error: string;
  code: string;
};

export type UpdatePatient500 = {
  error: string;
  code: string;
};

export type ListProtocolsParams = {
  activeOnly?: ListProtocolsActiveOnly;
};

export type ListProtocolsActiveOnly =
  (typeof ListProtocolsActiveOnly)[keyof typeof ListProtocolsActiveOnly];

export const ListProtocolsActiveOnly = {
  true: "true",
  false: "false",
} as const;

export type ListProtocols200ProtocolsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  slug: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type ListProtocols200 = {
  protocols: ListProtocols200ProtocolsItem[];
};

export type ListProtocols401 = {
  error: string;
  code: string;
};

export type ListProtocols500 = {
  error: string;
  code: string;
};

export type GetProtocol200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  /** @nullable */
  description: string | null;
  /** @nullable */
  slug: string | null;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
};

export type GetProtocol401 = {
  error: string;
  code: string;
};

export type GetProtocol404 = {
  error: string;
  code: string;
};

export type GetProtocol500 = {
  error: string;
  code: string;
};

export type ListStructuredAssessments200AssessmentsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  protocolId: string;
  protocolName?: string;
  payload: unknown;
  assessedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type ListStructuredAssessments200 = {
  assessments: ListStructuredAssessments200AssessmentsItem[];
};

export type ListStructuredAssessments401 = {
  error: string;
  code: string;
};

export type ListStructuredAssessments404 = {
  error: string;
  code: string;
};

export type ListStructuredAssessments500 = {
  error: string;
  code: string;
};

export type CreateStructuredAssessmentBodyPayload = { [key: string]: unknown };

export type CreateStructuredAssessmentBody = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  protocolId: string;
  payload: CreateStructuredAssessmentBodyPayload;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  assessedAt: string;
};

export type CreateStructuredAssessment201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  protocolId: string;
  payload: unknown;
  assessedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type CreateStructuredAssessment401 = {
  error: string;
  code: string;
};

export type CreateStructuredAssessment404 = {
  error: string;
  code: string;
};

export type CreateStructuredAssessment500 = {
  error: string;
  code: string;
};

export type GetStructuredAssessment200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  protocolId: string;
  protocolName?: string;
  payload: unknown;
  assessedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type GetStructuredAssessment401 = {
  error: string;
  code: string;
};

export type GetStructuredAssessment404 = {
  error: string;
  code: string;
};

export type GetStructuredAssessment500 = {
  error: string;
  code: string;
};

export type UpdateStructuredAssessmentBodyPayload = { [key: string]: unknown };

export type UpdateStructuredAssessmentBody = {
  payload?: UpdateStructuredAssessmentBodyPayload;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  assessedAt?: string;
};

export type UpdateStructuredAssessment200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  protocolId: string;
  payload: unknown;
  assessedAt: string;
  createdAt: string;
  updatedAt: string;
};

export type UpdateStructuredAssessment401 = {
  error: string;
  code: string;
};

export type UpdateStructuredAssessment404 = {
  error: string;
  code: string;
};

export type UpdateStructuredAssessment500 = {
  error: string;
  code: string;
};

export type ListUnstructuredObservations200ObservationsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  content: string;
  observedAt: string;
  /** @nullable */
  tags: string | null;
  createdAt: string;
  updatedAt: string;
};

export type ListUnstructuredObservations200 = {
  observations: ListUnstructuredObservations200ObservationsItem[];
};

export type ListUnstructuredObservations401 = {
  error: string;
  code: string;
};

export type ListUnstructuredObservations404 = {
  error: string;
  code: string;
};

export type ListUnstructuredObservations500 = {
  error: string;
  code: string;
};

export type CreateUnstructuredObservationBody = {
  /** @minLength 1 */
  content: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  observedAt: string;
  /** @nullable */
  tags?: string | null;
};

export type CreateUnstructuredObservation201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  content: string;
  observedAt: string;
  /** @nullable */
  tags: string | null;
  createdAt: string;
  updatedAt: string;
};

export type CreateUnstructuredObservation401 = {
  error: string;
  code: string;
};

export type CreateUnstructuredObservation404 = {
  error: string;
  code: string;
};

export type CreateUnstructuredObservation500 = {
  error: string;
  code: string;
};

export type GetUnstructuredObservation200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  content: string;
  observedAt: string;
  /** @nullable */
  tags: string | null;
  createdAt: string;
  updatedAt: string;
};

export type GetUnstructuredObservation401 = {
  error: string;
  code: string;
};

export type GetUnstructuredObservation404 = {
  error: string;
  code: string;
};

export type GetUnstructuredObservation500 = {
  error: string;
  code: string;
};

export type UpdateUnstructuredObservationBody = {
  /** @minLength 1 */
  content?: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  observedAt?: string;
  /** @nullable */
  tags?: string | null;
};

export type UpdateUnstructuredObservation200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  content: string;
  observedAt: string;
  /** @nullable */
  tags: string | null;
  createdAt: string;
  updatedAt: string;
};

export type UpdateUnstructuredObservation401 = {
  error: string;
  code: string;
};

export type UpdateUnstructuredObservation404 = {
  error: string;
  code: string;
};

export type UpdateUnstructuredObservation500 = {
  error: string;
  code: string;
};

export type ListAiResponses200AiResponsesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @nullable */
  inputSummary: string | null;
  hypotheses: string;
  /** @nullable */
  activitiesJson: string | null;
  /** @nullable */
  scalesJson: string | null;
  createdAt: string;
};

export type ListAiResponses200 = {
  aiResponses: ListAiResponses200AiResponsesItem[];
};

export type ListAiResponses401 = {
  error: string;
  code: string;
};

export type ListAiResponses404 = {
  error: string;
  code: string;
};

export type ListAiResponses500 = {
  error: string;
  code: string;
};

export type CreateAiResponseBody = {
  /** @minLength 1 */
  hypotheses: string;
  /** @nullable */
  activitiesJson?: string | null;
  /** @nullable */
  scalesJson?: string | null;
  /** @nullable */
  inputSummary?: string | null;
};

export type CreateAiResponse201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @nullable */
  inputSummary: string | null;
  hypotheses: string;
  /** @nullable */
  activitiesJson: string | null;
  /** @nullable */
  scalesJson: string | null;
  createdAt: string;
};

export type CreateAiResponse401 = {
  error: string;
  code: string;
};

export type CreateAiResponse404 = {
  error: string;
  code: string;
};

export type CreateAiResponse500 = {
  error: string;
  code: string;
};

export type GenerateAiAnalysisBody = {
  assessmentIds?: string[];
  observationIds?: string[];
};

export type GenerateAiAnalysis201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @nullable */
  inputSummary: string | null;
  hypotheses: string;
  /** @nullable */
  activitiesJson: string | null;
  /** @nullable */
  scalesJson: string | null;
  createdAt: string;
};

export type GenerateAiAnalysis401 = {
  error: string;
  code: string;
};

export type GenerateAiAnalysis404 = {
  error: string;
  code: string;
};

export type GenerateAiAnalysis429 = {
  error: string;
  code: string;
};

export type GenerateAiAnalysis500 = {
  error: string;
  code: string;
};

export type GenerateAiAnalysis502 = {
  error: string;
  code: string;
};

export type GetAiResponse200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  patientId: string;
  /** @nullable */
  inputSummary: string | null;
  hypotheses: string;
  /** @nullable */
  activitiesJson: string | null;
  /** @nullable */
  scalesJson: string | null;
  createdAt: string;
};

export type GetAiResponse401 = {
  error: string;
  code: string;
};

export type GetAiResponse404 = {
  error: string;
  code: string;
};

export type GetAiResponse500 = {
  error: string;
  code: string;
};

export type Get200 = {
  message: string;
};

/**
 * @summary Dados do profissional logado
 */
export type getMeResponse200 = {
  data: GetMe200;
  status: 200;
};

export type getMeResponse401 = {
  data: GetMe401;
  status: 401;
};

export type getMeResponse500 = {
  data: GetMe500;
  status: 500;
};

export type getMeResponseSuccess = getMeResponse200 & {
  headers: Headers;
};
export type getMeResponseError = (getMeResponse401 | getMeResponse500) & {
  headers: Headers;
};

export type getMeResponse = getMeResponseSuccess | getMeResponseError;

export const getGetMeUrl = () => {
  return `/me/`;
};

export const getMe = async (options?: RequestInit): Promise<getMeResponse> => {
  return customFetch<getMeResponse>(getGetMeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Listar pacientes do profissional
 */
export type listPatientsResponse200 = {
  data: ListPatients200;
  status: 200;
};

export type listPatientsResponse401 = {
  data: ListPatients401;
  status: 401;
};

export type listPatientsResponse500 = {
  data: ListPatients500;
  status: 500;
};

export type listPatientsResponseSuccess = listPatientsResponse200 & {
  headers: Headers;
};
export type listPatientsResponseError = (
  | listPatientsResponse401
  | listPatientsResponse500
) & {
  headers: Headers;
};

export type listPatientsResponse =
  | listPatientsResponseSuccess
  | listPatientsResponseError;

export const getListPatientsUrl = (params?: ListPatientsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/patients/?${stringifiedParams}`
    : `/patients/`;
};

export const listPatients = async (
  params?: ListPatientsParams,
  options?: RequestInit,
): Promise<listPatientsResponse> => {
  return customFetch<listPatientsResponse>(getListPatientsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Criar paciente
 */
export type createPatientResponse201 = {
  data: CreatePatient201;
  status: 201;
};

export type createPatientResponse401 = {
  data: CreatePatient401;
  status: 401;
};

export type createPatientResponse500 = {
  data: CreatePatient500;
  status: 500;
};

export type createPatientResponseSuccess = createPatientResponse201 & {
  headers: Headers;
};
export type createPatientResponseError = (
  | createPatientResponse401
  | createPatientResponse500
) & {
  headers: Headers;
};

export type createPatientResponse =
  | createPatientResponseSuccess
  | createPatientResponseError;

export const getCreatePatientUrl = () => {
  return `/patients/`;
};

export const createPatient = async (
  createPatientBody: CreatePatientBody,
  options?: RequestInit,
): Promise<createPatientResponse> => {
  return customFetch<createPatientResponse>(getCreatePatientUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createPatientBody),
  });
};

/**
 * @summary Obter paciente por ID
 */
export type getPatientResponse200 = {
  data: GetPatient200;
  status: 200;
};

export type getPatientResponse401 = {
  data: GetPatient401;
  status: 401;
};

export type getPatientResponse404 = {
  data: GetPatient404;
  status: 404;
};

export type getPatientResponse500 = {
  data: GetPatient500;
  status: 500;
};

export type getPatientResponseSuccess = getPatientResponse200 & {
  headers: Headers;
};
export type getPatientResponseError = (
  | getPatientResponse401
  | getPatientResponse404
  | getPatientResponse500
) & {
  headers: Headers;
};

export type getPatientResponse =
  | getPatientResponseSuccess
  | getPatientResponseError;

export const getGetPatientUrl = (patientId: string) => {
  return `/patients/${patientId}`;
};

export const getPatient = async (
  patientId: string,
  options?: RequestInit,
): Promise<getPatientResponse> => {
  return customFetch<getPatientResponse>(getGetPatientUrl(patientId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Atualizar paciente
 */
export type updatePatientResponse200 = {
  data: UpdatePatient200;
  status: 200;
};

export type updatePatientResponse401 = {
  data: UpdatePatient401;
  status: 401;
};

export type updatePatientResponse404 = {
  data: UpdatePatient404;
  status: 404;
};

export type updatePatientResponse500 = {
  data: UpdatePatient500;
  status: 500;
};

export type updatePatientResponseSuccess = updatePatientResponse200 & {
  headers: Headers;
};
export type updatePatientResponseError = (
  | updatePatientResponse401
  | updatePatientResponse404
  | updatePatientResponse500
) & {
  headers: Headers;
};

export type updatePatientResponse =
  | updatePatientResponseSuccess
  | updatePatientResponseError;

export const getUpdatePatientUrl = (patientId: string) => {
  return `/patients/${patientId}`;
};

export const updatePatient = async (
  patientId: string,
  updatePatientBody: UpdatePatientBody,
  options?: RequestInit,
): Promise<updatePatientResponse> => {
  return customFetch<updatePatientResponse>(getUpdatePatientUrl(patientId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updatePatientBody),
  });
};

/**
 * @summary Listar protocolos (tipos de avaliação)
 */
export type listProtocolsResponse200 = {
  data: ListProtocols200;
  status: 200;
};

export type listProtocolsResponse401 = {
  data: ListProtocols401;
  status: 401;
};

export type listProtocolsResponse500 = {
  data: ListProtocols500;
  status: 500;
};

export type listProtocolsResponseSuccess = listProtocolsResponse200 & {
  headers: Headers;
};
export type listProtocolsResponseError = (
  | listProtocolsResponse401
  | listProtocolsResponse500
) & {
  headers: Headers;
};

export type listProtocolsResponse =
  | listProtocolsResponseSuccess
  | listProtocolsResponseError;

export const getListProtocolsUrl = (params?: ListProtocolsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/protocols/?${stringifiedParams}`
    : `/protocols/`;
};

export const listProtocols = async (
  params?: ListProtocolsParams,
  options?: RequestInit,
): Promise<listProtocolsResponse> => {
  return customFetch<listProtocolsResponse>(getListProtocolsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Obter protocolo por ID
 */
export type getProtocolResponse200 = {
  data: GetProtocol200;
  status: 200;
};

export type getProtocolResponse401 = {
  data: GetProtocol401;
  status: 401;
};

export type getProtocolResponse404 = {
  data: GetProtocol404;
  status: 404;
};

export type getProtocolResponse500 = {
  data: GetProtocol500;
  status: 500;
};

export type getProtocolResponseSuccess = getProtocolResponse200 & {
  headers: Headers;
};
export type getProtocolResponseError = (
  | getProtocolResponse401
  | getProtocolResponse404
  | getProtocolResponse500
) & {
  headers: Headers;
};

export type getProtocolResponse =
  | getProtocolResponseSuccess
  | getProtocolResponseError;

export const getGetProtocolUrl = (protocolId: string) => {
  return `/protocols/${protocolId}`;
};

export const getProtocol = async (
  protocolId: string,
  options?: RequestInit,
): Promise<getProtocolResponse> => {
  return customFetch<getProtocolResponse>(getGetProtocolUrl(protocolId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Listar avaliações estruturadas do paciente
 */
export type listStructuredAssessmentsResponse200 = {
  data: ListStructuredAssessments200;
  status: 200;
};

export type listStructuredAssessmentsResponse401 = {
  data: ListStructuredAssessments401;
  status: 401;
};

export type listStructuredAssessmentsResponse404 = {
  data: ListStructuredAssessments404;
  status: 404;
};

export type listStructuredAssessmentsResponse500 = {
  data: ListStructuredAssessments500;
  status: 500;
};

export type listStructuredAssessmentsResponseSuccess =
  listStructuredAssessmentsResponse200 & {
    headers: Headers;
  };
export type listStructuredAssessmentsResponseError = (
  | listStructuredAssessmentsResponse401
  | listStructuredAssessmentsResponse404
  | listStructuredAssessmentsResponse500
) & {
  headers: Headers;
};

export type listStructuredAssessmentsResponse =
  | listStructuredAssessmentsResponseSuccess
  | listStructuredAssessmentsResponseError;

export const getListStructuredAssessmentsUrl = (patientId: string) => {
  return `/patients/${patientId}/assessments/`;
};

export const listStructuredAssessments = async (
  patientId: string,
  options?: RequestInit,
): Promise<listStructuredAssessmentsResponse> => {
  return customFetch<listStructuredAssessmentsResponse>(
    getListStructuredAssessmentsUrl(patientId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Criar avaliação estruturada
 */
export type createStructuredAssessmentResponse201 = {
  data: CreateStructuredAssessment201;
  status: 201;
};

export type createStructuredAssessmentResponse401 = {
  data: CreateStructuredAssessment401;
  status: 401;
};

export type createStructuredAssessmentResponse404 = {
  data: CreateStructuredAssessment404;
  status: 404;
};

export type createStructuredAssessmentResponse500 = {
  data: CreateStructuredAssessment500;
  status: 500;
};

export type createStructuredAssessmentResponseSuccess =
  createStructuredAssessmentResponse201 & {
    headers: Headers;
  };
export type createStructuredAssessmentResponseError = (
  | createStructuredAssessmentResponse401
  | createStructuredAssessmentResponse404
  | createStructuredAssessmentResponse500
) & {
  headers: Headers;
};

export type createStructuredAssessmentResponse =
  | createStructuredAssessmentResponseSuccess
  | createStructuredAssessmentResponseError;

export const getCreateStructuredAssessmentUrl = (patientId: string) => {
  return `/patients/${patientId}/assessments/`;
};

export const createStructuredAssessment = async (
  patientId: string,
  createStructuredAssessmentBody: CreateStructuredAssessmentBody,
  options?: RequestInit,
): Promise<createStructuredAssessmentResponse> => {
  return customFetch<createStructuredAssessmentResponse>(
    getCreateStructuredAssessmentUrl(patientId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createStructuredAssessmentBody),
    },
  );
};

/**
 * @summary Obter avaliação estruturada por ID
 */
export type getStructuredAssessmentResponse200 = {
  data: GetStructuredAssessment200;
  status: 200;
};

export type getStructuredAssessmentResponse401 = {
  data: GetStructuredAssessment401;
  status: 401;
};

export type getStructuredAssessmentResponse404 = {
  data: GetStructuredAssessment404;
  status: 404;
};

export type getStructuredAssessmentResponse500 = {
  data: GetStructuredAssessment500;
  status: 500;
};

export type getStructuredAssessmentResponseSuccess =
  getStructuredAssessmentResponse200 & {
    headers: Headers;
  };
export type getStructuredAssessmentResponseError = (
  | getStructuredAssessmentResponse401
  | getStructuredAssessmentResponse404
  | getStructuredAssessmentResponse500
) & {
  headers: Headers;
};

export type getStructuredAssessmentResponse =
  | getStructuredAssessmentResponseSuccess
  | getStructuredAssessmentResponseError;

export const getGetStructuredAssessmentUrl = (
  patientId: string,
  assessmentId: string,
) => {
  return `/patients/${patientId}/assessments/${assessmentId}`;
};

export const getStructuredAssessment = async (
  patientId: string,
  assessmentId: string,
  options?: RequestInit,
): Promise<getStructuredAssessmentResponse> => {
  return customFetch<getStructuredAssessmentResponse>(
    getGetStructuredAssessmentUrl(patientId, assessmentId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Atualizar avaliação estruturada
 */
export type updateStructuredAssessmentResponse200 = {
  data: UpdateStructuredAssessment200;
  status: 200;
};

export type updateStructuredAssessmentResponse401 = {
  data: UpdateStructuredAssessment401;
  status: 401;
};

export type updateStructuredAssessmentResponse404 = {
  data: UpdateStructuredAssessment404;
  status: 404;
};

export type updateStructuredAssessmentResponse500 = {
  data: UpdateStructuredAssessment500;
  status: 500;
};

export type updateStructuredAssessmentResponseSuccess =
  updateStructuredAssessmentResponse200 & {
    headers: Headers;
  };
export type updateStructuredAssessmentResponseError = (
  | updateStructuredAssessmentResponse401
  | updateStructuredAssessmentResponse404
  | updateStructuredAssessmentResponse500
) & {
  headers: Headers;
};

export type updateStructuredAssessmentResponse =
  | updateStructuredAssessmentResponseSuccess
  | updateStructuredAssessmentResponseError;

export const getUpdateStructuredAssessmentUrl = (
  patientId: string,
  assessmentId: string,
) => {
  return `/patients/${patientId}/assessments/${assessmentId}`;
};

export const updateStructuredAssessment = async (
  patientId: string,
  assessmentId: string,
  updateStructuredAssessmentBody: UpdateStructuredAssessmentBody,
  options?: RequestInit,
): Promise<updateStructuredAssessmentResponse> => {
  return customFetch<updateStructuredAssessmentResponse>(
    getUpdateStructuredAssessmentUrl(patientId, assessmentId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateStructuredAssessmentBody),
    },
  );
};

/**
 * @summary Listar observações não estruturadas do paciente
 */
export type listUnstructuredObservationsResponse200 = {
  data: ListUnstructuredObservations200;
  status: 200;
};

export type listUnstructuredObservationsResponse401 = {
  data: ListUnstructuredObservations401;
  status: 401;
};

export type listUnstructuredObservationsResponse404 = {
  data: ListUnstructuredObservations404;
  status: 404;
};

export type listUnstructuredObservationsResponse500 = {
  data: ListUnstructuredObservations500;
  status: 500;
};

export type listUnstructuredObservationsResponseSuccess =
  listUnstructuredObservationsResponse200 & {
    headers: Headers;
  };
export type listUnstructuredObservationsResponseError = (
  | listUnstructuredObservationsResponse401
  | listUnstructuredObservationsResponse404
  | listUnstructuredObservationsResponse500
) & {
  headers: Headers;
};

export type listUnstructuredObservationsResponse =
  | listUnstructuredObservationsResponseSuccess
  | listUnstructuredObservationsResponseError;

export const getListUnstructuredObservationsUrl = (patientId: string) => {
  return `/patients/${patientId}/observations/`;
};

export const listUnstructuredObservations = async (
  patientId: string,
  options?: RequestInit,
): Promise<listUnstructuredObservationsResponse> => {
  return customFetch<listUnstructuredObservationsResponse>(
    getListUnstructuredObservationsUrl(patientId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Criar observação não estruturada
 */
export type createUnstructuredObservationResponse201 = {
  data: CreateUnstructuredObservation201;
  status: 201;
};

export type createUnstructuredObservationResponse401 = {
  data: CreateUnstructuredObservation401;
  status: 401;
};

export type createUnstructuredObservationResponse404 = {
  data: CreateUnstructuredObservation404;
  status: 404;
};

export type createUnstructuredObservationResponse500 = {
  data: CreateUnstructuredObservation500;
  status: 500;
};

export type createUnstructuredObservationResponseSuccess =
  createUnstructuredObservationResponse201 & {
    headers: Headers;
  };
export type createUnstructuredObservationResponseError = (
  | createUnstructuredObservationResponse401
  | createUnstructuredObservationResponse404
  | createUnstructuredObservationResponse500
) & {
  headers: Headers;
};

export type createUnstructuredObservationResponse =
  | createUnstructuredObservationResponseSuccess
  | createUnstructuredObservationResponseError;

export const getCreateUnstructuredObservationUrl = (patientId: string) => {
  return `/patients/${patientId}/observations/`;
};

export const createUnstructuredObservation = async (
  patientId: string,
  createUnstructuredObservationBody: CreateUnstructuredObservationBody,
  options?: RequestInit,
): Promise<createUnstructuredObservationResponse> => {
  return customFetch<createUnstructuredObservationResponse>(
    getCreateUnstructuredObservationUrl(patientId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createUnstructuredObservationBody),
    },
  );
};

/**
 * @summary Obter observação por ID
 */
export type getUnstructuredObservationResponse200 = {
  data: GetUnstructuredObservation200;
  status: 200;
};

export type getUnstructuredObservationResponse401 = {
  data: GetUnstructuredObservation401;
  status: 401;
};

export type getUnstructuredObservationResponse404 = {
  data: GetUnstructuredObservation404;
  status: 404;
};

export type getUnstructuredObservationResponse500 = {
  data: GetUnstructuredObservation500;
  status: 500;
};

export type getUnstructuredObservationResponseSuccess =
  getUnstructuredObservationResponse200 & {
    headers: Headers;
  };
export type getUnstructuredObservationResponseError = (
  | getUnstructuredObservationResponse401
  | getUnstructuredObservationResponse404
  | getUnstructuredObservationResponse500
) & {
  headers: Headers;
};

export type getUnstructuredObservationResponse =
  | getUnstructuredObservationResponseSuccess
  | getUnstructuredObservationResponseError;

export const getGetUnstructuredObservationUrl = (
  patientId: string,
  observationId: string,
) => {
  return `/patients/${patientId}/observations/${observationId}`;
};

export const getUnstructuredObservation = async (
  patientId: string,
  observationId: string,
  options?: RequestInit,
): Promise<getUnstructuredObservationResponse> => {
  return customFetch<getUnstructuredObservationResponse>(
    getGetUnstructuredObservationUrl(patientId, observationId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Atualizar observação não estruturada
 */
export type updateUnstructuredObservationResponse200 = {
  data: UpdateUnstructuredObservation200;
  status: 200;
};

export type updateUnstructuredObservationResponse401 = {
  data: UpdateUnstructuredObservation401;
  status: 401;
};

export type updateUnstructuredObservationResponse404 = {
  data: UpdateUnstructuredObservation404;
  status: 404;
};

export type updateUnstructuredObservationResponse500 = {
  data: UpdateUnstructuredObservation500;
  status: 500;
};

export type updateUnstructuredObservationResponseSuccess =
  updateUnstructuredObservationResponse200 & {
    headers: Headers;
  };
export type updateUnstructuredObservationResponseError = (
  | updateUnstructuredObservationResponse401
  | updateUnstructuredObservationResponse404
  | updateUnstructuredObservationResponse500
) & {
  headers: Headers;
};

export type updateUnstructuredObservationResponse =
  | updateUnstructuredObservationResponseSuccess
  | updateUnstructuredObservationResponseError;

export const getUpdateUnstructuredObservationUrl = (
  patientId: string,
  observationId: string,
) => {
  return `/patients/${patientId}/observations/${observationId}`;
};

export const updateUnstructuredObservation = async (
  patientId: string,
  observationId: string,
  updateUnstructuredObservationBody: UpdateUnstructuredObservationBody,
  options?: RequestInit,
): Promise<updateUnstructuredObservationResponse> => {
  return customFetch<updateUnstructuredObservationResponse>(
    getUpdateUnstructuredObservationUrl(patientId, observationId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateUnstructuredObservationBody),
    },
  );
};

/**
 * @summary Listar respostas da IA do paciente
 */
export type listAiResponsesResponse200 = {
  data: ListAiResponses200;
  status: 200;
};

export type listAiResponsesResponse401 = {
  data: ListAiResponses401;
  status: 401;
};

export type listAiResponsesResponse404 = {
  data: ListAiResponses404;
  status: 404;
};

export type listAiResponsesResponse500 = {
  data: ListAiResponses500;
  status: 500;
};

export type listAiResponsesResponseSuccess = listAiResponsesResponse200 & {
  headers: Headers;
};
export type listAiResponsesResponseError = (
  | listAiResponsesResponse401
  | listAiResponsesResponse404
  | listAiResponsesResponse500
) & {
  headers: Headers;
};

export type listAiResponsesResponse =
  | listAiResponsesResponseSuccess
  | listAiResponsesResponseError;

export const getListAiResponsesUrl = (patientId: string) => {
  return `/patients/${patientId}/ai-responses/`;
};

export const listAiResponses = async (
  patientId: string,
  options?: RequestInit,
): Promise<listAiResponsesResponse> => {
  return customFetch<listAiResponsesResponse>(
    getListAiResponsesUrl(patientId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Registrar resposta da IA manualmente (hipóteses, atividades, escalas)
 */
export type createAiResponseResponse201 = {
  data: CreateAiResponse201;
  status: 201;
};

export type createAiResponseResponse401 = {
  data: CreateAiResponse401;
  status: 401;
};

export type createAiResponseResponse404 = {
  data: CreateAiResponse404;
  status: 404;
};

export type createAiResponseResponse500 = {
  data: CreateAiResponse500;
  status: 500;
};

export type createAiResponseResponseSuccess = createAiResponseResponse201 & {
  headers: Headers;
};
export type createAiResponseResponseError = (
  | createAiResponseResponse401
  | createAiResponseResponse404
  | createAiResponseResponse500
) & {
  headers: Headers;
};

export type createAiResponseResponse =
  | createAiResponseResponseSuccess
  | createAiResponseResponseError;

export const getCreateAiResponseUrl = (patientId: string) => {
  return `/patients/${patientId}/ai-responses/`;
};

export const createAiResponse = async (
  patientId: string,
  createAiResponseBody: CreateAiResponseBody,
  options?: RequestInit,
): Promise<createAiResponseResponse> => {
  return customFetch<createAiResponseResponse>(
    getCreateAiResponseUrl(patientId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createAiResponseBody),
    },
  );
};

/**
 * @summary Gerar análise com IA (hipóteses, atividades, escalas) a partir dos dados do paciente
 */
export type generateAiAnalysisResponse201 = {
  data: GenerateAiAnalysis201;
  status: 201;
};

export type generateAiAnalysisResponse401 = {
  data: GenerateAiAnalysis401;
  status: 401;
};

export type generateAiAnalysisResponse404 = {
  data: GenerateAiAnalysis404;
  status: 404;
};

export type generateAiAnalysisResponse429 = {
  data: GenerateAiAnalysis429;
  status: 429;
};

export type generateAiAnalysisResponse500 = {
  data: GenerateAiAnalysis500;
  status: 500;
};

export type generateAiAnalysisResponse502 = {
  data: GenerateAiAnalysis502;
  status: 502;
};

export type generateAiAnalysisResponseSuccess =
  generateAiAnalysisResponse201 & {
    headers: Headers;
  };
export type generateAiAnalysisResponseError = (
  | generateAiAnalysisResponse401
  | generateAiAnalysisResponse404
  | generateAiAnalysisResponse429
  | generateAiAnalysisResponse500
  | generateAiAnalysisResponse502
) & {
  headers: Headers;
};

export type generateAiAnalysisResponse =
  | generateAiAnalysisResponseSuccess
  | generateAiAnalysisResponseError;

export const getGenerateAiAnalysisUrl = (patientId: string) => {
  return `/patients/${patientId}/ai-responses/generate`;
};

export const generateAiAnalysis = async (
  patientId: string,
  generateAiAnalysisBody: GenerateAiAnalysisBody,
  options?: RequestInit,
): Promise<generateAiAnalysisResponse> => {
  return customFetch<generateAiAnalysisResponse>(
    getGenerateAiAnalysisUrl(patientId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(generateAiAnalysisBody),
    },
  );
};

/**
 * @summary Obter resposta da IA por ID
 */
export type getAiResponseResponse200 = {
  data: GetAiResponse200;
  status: 200;
};

export type getAiResponseResponse401 = {
  data: GetAiResponse401;
  status: 401;
};

export type getAiResponseResponse404 = {
  data: GetAiResponse404;
  status: 404;
};

export type getAiResponseResponse500 = {
  data: GetAiResponse500;
  status: 500;
};

export type getAiResponseResponseSuccess = getAiResponseResponse200 & {
  headers: Headers;
};
export type getAiResponseResponseError = (
  | getAiResponseResponse401
  | getAiResponseResponse404
  | getAiResponseResponse500
) & {
  headers: Headers;
};

export type getAiResponseResponse =
  | getAiResponseResponseSuccess
  | getAiResponseResponseError;

export const getGetAiResponseUrl = (
  patientId: string,
  aiResponseId: string,
) => {
  return `/patients/${patientId}/ai-responses/${aiResponseId}`;
};

export const getAiResponse = async (
  patientId: string,
  aiResponseId: string,
  options?: RequestInit,
): Promise<getAiResponseResponse> => {
  return customFetch<getAiResponseResponse>(
    getGetAiResponseUrl(patientId, aiResponseId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * Health check
 */
export type getResponse200 = {
  data: Get200;
  status: 200;
};

export type getResponseSuccess = getResponse200 & {
  headers: Headers;
};
export type getResponse = getResponseSuccess;

export const getGetUrl = () => {
  return `/`;
};

export const get = async (options?: RequestInit): Promise<getResponse> => {
  return customFetch<getResponse>(getGetUrl(), {
    ...options,
    method: "GET",
  });
};
